/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  v3SideBar: [
    'v3/intro',
    {
      type: 'category',
      label: 'Copy Trade',
      link: {
        type: 'generated-index',
        title: 'Copy Trade Guides',
        description:
            "Please note that you are not allowed to access this API once you upgrade to new Copy trading. Check changelog for more information",
        image: '/img/docusaurus.png',
      },
      items: [
        {
          type: 'category',
          label: 'REST API',
          items: [
            {
              type: 'category',
              label: 'Market data',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v3/copy-trade/rest-public'
                }
              ]
            },
            {
              type: 'category',
              label: 'Trade',
              items: [
                {
                  type: 'category',
                  label: 'Order',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'v3/copy-trade/rest-trade/order'
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'Position',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'v3/copy-trade/rest-trade/position'
                    }
                  ]
                },
                {
                  type: 'category',
                  label: 'Account',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'v3/copy-trade/rest-trade/account'
                    }
                  ]
                }
              ]
            },
          ]
        },
        /*{
          type: 'category',
          label: 'WebSocket Stream',
          items: [
              'v3/copy-trade/wss-authentication',
            {
              type: 'category',
              label: 'Public Channel',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v3/copy-trade/wss-public'
                }
              ]
            },
            {
              type: 'category',
              label: 'Private Channel',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'v3/copy-trade/wss-private'
                }
              ]
            }
          ]
        },*/
        'v3/copy-trade/rate-limit',
        'v3/copy-trade/enum',
        'v3/copy-trade/error',
      ]
    },
    {
      type: 'category',
      label: 'Asset',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v3/asset'
        }
      ]
    },
    {
      type: 'category',
      label: 'Market',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v3/market'
        }
      ]
    },
    {
      type: 'category',
      label: 'Trade',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v3/order'
        }
      ]
    },
    {
      type: 'category',
      label: 'Position',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v3/position'
        }
      ]
    },
    {
      type: 'category',
      label: 'Account',
      items: [
        {
          type: 'autogenerated',
          dirName: 'v3/account'
        }
      ]
    },
    {
      type: 'category',
      label: 'WebSocket Stream',
      items: [
        'v3/websocket/wss-authentication',
        {
          type: 'category',
          label: 'Public',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v3/websocket/public'
            }
          ]
        },
        {
          type: 'category',
          label: 'Private',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v3/websocket/private'
            }
          ]
        }
      ]
    },
    'v3/rate-limit',
    'v3/enum',
    'v3/error',
  ],
  changelogSidebar: [
    "changelog/v3",
  ],
};

module.exports = sidebars;
